### ISSUE TITLE
Support Gnome 45

### ISSUE THREAD

**Issue by schlagmichdoch** [lucaswerkmeister/activate-window-by-title#5]
Thanks for this extension and for implementing #2
As Gnome 45 is around the corner, please add support for it to your extension!

Not sure, whether you need to tweak sth. apart from https://github.com/lucaswerkmeister/activate-window-by-title/blob/main/metadata.json#L6

**Comment by lucaswerkmeister** [comment]
Done in 5f4b5c04317c04e7ab2ce5b60999e8c389d693a9, which was already available in a branch before this issue was created.

As I don’t really fancy incrementing the issue counter for every new gnome release… would you mind at least waiting with these tasks until after the release has actually happened?
